# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Card.create(rank: "A", suit: 'H', value: -1)
Card.create(rank: "A", suit: 'D', value: -1)
Card.create(rank: "A", suit: 'C', value: -1)
Card.create(rank: "A", suit: 'S', value: -1)
Card.create(rank: "2", suit: 'H', value: 1)
Card.create(rank: "2", suit: 'D', value: 1)
Card.create(rank: "2", suit: 'C', value: 1)
Card.create(rank: "2", suit: 'S', value: 1)
Card.create(rank: "3", suit: 'H', value: 1)
Card.create(rank: "3", suit: 'D', value: 1)
Card.create(rank: "3", suit: 'C', value: 1)
Card.create(rank: "3", suit: 'S', value: 1)
Card.create(rank: "4", suit: 'H', value: 1)
Card.create(rank: "4", suit: 'D', value: 1)
Card.create(rank: "4", suit: 'C', value: 1)
Card.create(rank: "4", suit: 'S', value: 1)
Card.create(rank: "5", suit: 'H', value: 1)
Card.create(rank: "5", suit: 'D', value: 1)
Card.create(rank: "5", suit: 'C', value: 1)
Card.create(rank: "5", suit: 'S', value: 1)
Card.create(rank: "6", suit: 'H', value: 1)
Card.create(rank: "6", suit: 'D', value: 1)
Card.create(rank: "6", suit: 'C', value: 1)
Card.create(rank: "6", suit: 'S', value: 1)
Card.create(rank: "7", suit: 'H', value: 0)
Card.create(rank: "7", suit: 'D', value: 0)
Card.create(rank: "7", suit: 'C', value: 0)
Card.create(rank: "7", suit: 'S', value: 0)
Card.create(rank: "8", suit: 'H', value: 0)
Card.create(rank: "8", suit: 'D', value: 0)
Card.create(rank: "8", suit: 'C', value: 0)
Card.create(rank: "8", suit: 'S', value: 0)
Card.create(rank: "9", suit: 'H', value: 0)
Card.create(rank: "9", suit: 'D', value: 0)
Card.create(rank: "9", suit: 'C', value: 0)
Card.create(rank: "9", suit: 'S', value: 0)
Card.create(rank: "10", suit: 'H', value: -1)
Card.create(rank: "10", suit: 'D', value: -1)
Card.create(rank: "10", suit: 'C', value: -1)
Card.create(rank: "10", suit: 'S', value: -1)
Card.create(rank: "J", suit: 'H', value: -1)
Card.create(rank: "J", suit: 'D', value: -1)
Card.create(rank: "J", suit: 'C', value: -1)
Card.create(rank: "J", suit: 'S', value: -1)
Card.create(rank: "Q", suit: 'H', value: -1)
Card.create(rank: "Q", suit: 'D', value: -1)
Card.create(rank: "Q", suit: 'C', value: -1)
Card.create(rank: "Q", suit: 'S', value: -1)
Card.create(rank: "K", suit: 'H', value: -1)
Card.create(rank: "K", suit: 'D', value: -1)
Card.create(rank: "K", suit: 'C', value: -1)
Card.create(rank: "K", suit: 'S', value: -1)
