# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Card.create(rank: "A", suit: '♥', value: -1, color: 'red')
Card.create(rank: "A", suit: '♦', value: -1, color: 'red')
Card.create(rank: "A", suit: '♣', value: -1, color: 'black')
Card.create(rank: "A", suit: '♠', value: -1, color: 'black')
Card.create(rank: "2", suit: '♥', value: 1, color: 'red')
Card.create(rank: "2", suit: '♦', value: 1, color: 'red')
Card.create(rank: "2", suit: '♣', value: 1, color: 'black')
Card.create(rank: "2", suit: '♠', value: 1, color: 'black')
Card.create(rank: "3", suit: '♥', value: 1, color: 'red')
Card.create(rank: "3", suit: '♦', value: 1, color: 'red')
Card.create(rank: "3", suit: '♣', value: 1, color: 'black')
Card.create(rank: "3", suit: '♠', value: 1, color: 'black')
Card.create(rank: "4", suit: '♥', value: 1, color: 'red')
Card.create(rank: "4", suit: '♦', value: 1, color: 'red')
Card.create(rank: "4", suit: '♣', value: 1, color: 'black')
Card.create(rank: "4", suit: '♠', value: 1, color: 'black')
Card.create(rank: "5", suit: '♥', value: 1, color: 'red')
Card.create(rank: "5", suit: '♦', value: 1, color: 'red')
Card.create(rank: "5", suit: '♣', value: 1, color: 'black')
Card.create(rank: "5", suit: '♠', value: 1, color: 'black')
Card.create(rank: "6", suit: '♥', value: 1, color: 'red')
Card.create(rank: "6", suit: '♦', value: 1, color: 'red')
Card.create(rank: "6", suit: '♣', value: 1, color: 'black')
Card.create(rank: "6", suit: '♠', value: 1, color: 'black')
Card.create(rank: "7", suit: '♥', value: 0, color: 'red')
Card.create(rank: "7", suit: '♦', value: 0, color: 'red')
Card.create(rank: "7", suit: '♣', value: 0, color: 'black')
Card.create(rank: "7", suit: '♠', value: 0, color: 'black')
Card.create(rank: "8", suit: '♥', value: 0, color: 'red')
Card.create(rank: "8", suit: '♦', value: 0, color: 'red')
Card.create(rank: "8", suit: '♣', value: 0, color: 'black')
Card.create(rank: "8", suit: '♠', value: 0, color: 'black')
Card.create(rank: "9", suit: '♥', value: 0, color: 'red')
Card.create(rank: "9", suit: '♦', value: 0, color: 'red')
Card.create(rank: "9", suit: '♣', value: 0, color: 'black')
Card.create(rank: "9", suit: '♠', value: 0, color: 'black')
Card.create(rank: "10", suit: '♥', value: -1, color: 'red')
Card.create(rank: "10", suit: '♦', value: -1, color: 'red')
Card.create(rank: "10", suit: '♣', value: -1, color: 'black')
Card.create(rank: "10", suit: '♠', value: -1, color: 'black')
Card.create(rank: "J", suit: '♥', value: -1, color: 'red')
Card.create(rank: "J", suit: '♦', value: -1, color: 'red')
Card.create(rank: "J", suit: '♣', value: -1, color: 'black')
Card.create(rank: "J", suit: '♠', value: -1, color: 'black')
Card.create(rank: "Q", suit: '♥', value: -1, color: 'red')
Card.create(rank: "Q", suit: '♦', value: -1, color: 'red')
Card.create(rank: "Q", suit: '♣', value: -1, color: 'black')
Card.create(rank: "Q", suit: '♠', value: -1, color: 'black')
Card.create(rank: "K", suit: '♥', value: -1, color: 'red')
Card.create(rank: "K", suit: '♦', value: -1, color: 'red')
Card.create(rank: "K", suit: '♣', value: -1, color: 'black')
Card.create(rank: "K", suit: '♠', value: -1, color: 'black')
